name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: dishari
          publish-profile: ${{ secrets.AZURE_SECRET }}
          package: ./backend # Deploy the whole backend folder
